### ISSUE TITLE
GSoC 2020 project

### ISSUE THREAD

**Issue by ridhishjain-zepto** [OWASP/www-project-juice-shop#1]
Hello, 
I am Ridhish Jain, Full-stack web developer, UG at IIT Dhanbad, India
I am a GSoC aspirant and would love to do GSoC in this organization.
Is this project going to be part of GSoC 2020?
I would love to contribute to it and also willing to work on new ideas (web development related).

**Comment by bkimminich** [comment]
Hi! If OWASP is selected as a GSoC organization this year, Juice Shop will participate and accept project applications,yes!

**Comment by ridhishjain-zepto** [comment]
That's great!!
Can you please tell me from where to start contributing

**Comment by bkimminich** [comment]
https://pwning.owasp-juice.shop/part3/contribution.html 👈😁

**Comment by bkimminich** [comment]
Some things which are always appreciated but not found in GitHub issues usually are

* Refactorings to reduce [technical debt](https://codeclimate.com/github/bkimminich/juice-shop)
* Adding new or fixing disabled unit or API tests to [increase code coverage](https://codeclimate.com/github/bkimminich/juice-shop)
* Helping with translations, e.g. into [Hindi via CrowdIn](https://crowdin.com/project/owasp-juice-shop/hi#)

**Comment by bkimminich** [comment]
Also, I recommend this general read before applying with a project proposal for OWASP: https://owasp.org/www-community/initiatives/gsoc/gsoc2020

**Comment by ridhishjain-zepto** [comment]
@bkimminich I wanted to join the slack channel for owasp for GSoC related issues...but it requires @owasp.org mail ID and I don't have one.
What to do?

**Comment by bkimminich** [comment]
Did you try https://owasp-slack.herokuapp.com to receive an invite? Alternatively you can also join the Juice Shop chat on https://gitter.im/bkimminich/juice-shop.
