### ISSUE TITLE
Make roadmap entries reusable

### ISSUE THREAD

**Issue by bkimminich** [OWASP/www-project-juice-shop#6]
Current the roadmap entries are duplicated (or notoriously out of sync) in two places:
* https://owasp.org/www-project-juice-shop/#div-news
* http://juice-shop.github.io/juice-shop/#/13

It would be great to store them in a JSON file in `_data` and show them in both places based on that file.

**Comment by zachesposito** [comment]
Hello happy Hacktober, I can take care of this
